### ISSUE TITLE
Maritime Trade lets you select a resource to receive without having one you can pick

### ISSUE THREAD

**Issue by jbonner6** [rysav/cs340spring2016#41]

**Comment by benjaminhafen** [comment]
Do you mean that you're able to select a resource to receive before selecting one to send? Because the game still doesn't let you make the trade unless you properly select a resource to send, we don't feel that this is a bug, since you can receive any item from a maritime trade without restriction. Only sending needs to have restrictions. We'll mark this as Not a Bug.
