### ISSUE TITLE
Discard Cards Error

### ISSUE THREAD

**Issue by rachel-trainor** [rysav/cs340spring2016#6]
After the first 7 was rolled and I had to discard half of my cards, every turn after that whenever I had more than 7 cards I had to discard half of them (no matter what anyone rolled before me or what I rolled). Picture for example.
![catanbug](https://cloud.githubusercontent.com/assets/16596996/15412690/c097b150-1de6-11e6-9be9-bcf427de757f.PNG)

**Comment by benjaminhafen** [comment]
Another bug is that rolling a 7 with 0 cards appears to cause a Discard dialog that cannot be closed since no cards can be discarded. I think this is just another effect of this same bug, though, so we won't list it separately.

![capture](https://cloud.githubusercontent.com/assets/7034327/15414612/81f1a4b6-1df9-11e6-94a3-42b1c43bd995.PNG)
