### ISSUE TITLE
Registering error

### ISSUE THREAD

**Issue by MasqueradeOfSilence** [rysav/cs340spring2016#86]
I tried registering, but put passwords that didn't match. When I clicked the register button, nothing happened instead of an error message showing up.

That being said, it did show the proper error message when I entered a username that was too long.

**Comment by rachel-trainor** [comment]
If you can recreate this and send me a screenshot, that would be really helpful because I've tried to recreate it multiple times and each time I get the correct error (screenshot below) so I'm not sure if it was a weird one time glitch that the error message didn't show up??

![password](https://cloud.githubusercontent.com/assets/16596996/15450165/e2884542-1f51-11e6-996f-5a2046d20107.PNG)
